[package]
name = "axum-hover"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.0"
dioxus-core = "0.5.1"
futures-channel = "0.3.30"
futures-util = "0.3.30"
mime = "0.3.17"
tokio = { version = "1.37.0", features = ["full"] }
